CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "GenelIstatistikler" (
    toplam_musteri integer NOT NULL,
    toplam_para numeric NOT NULL,
    toplam_islem integer NOT NULL,
    toplam_risk integer NOT NULL
);

CREATE TABLE musteriler (
    musteri_id integer GENERATED BY DEFAULT AS IDENTITY,
    ad character varying(50) NOT NULL,
    soyad character varying(50) NOT NULL,
    tc_kimlik_no character(11) NOT NULL,
    sifre character varying(50) NOT NULL,
    rol character varying(20) DEFAULT ('MUSTERI'::character varying),
    kayit_tarihi timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT musteriler_pkey PRIMARY KEY (musteri_id)
);

CREATE TABLE risk_masasi (
    risk_id integer GENERATED BY DEFAULT AS IDENTITY,
    hesap_id integer,
    supheli_olay character varying(200),
    olay_tarihi timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT risk_masasi_pkey PRIMARY KEY (risk_id)
);

CREATE TABLE hesaplar (
    hesap_id integer GENERATED BY DEFAULT AS IDENTITY,
    musteri_id integer NOT NULL,
    hesap_no character varying(20) NOT NULL,
    hesap_turu character varying(20) DEFAULT 'VADESIZ',
    bakiye numeric(15,2) DEFAULT (0.00),
    aktif_mi boolean DEFAULT TRUE,
    olusturma_tarihi timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT hesaplar_pkey PRIMARY KEY (hesap_id),
    CONSTRAINT fk_musteri FOREIGN KEY (musteri_id) REFERENCES musteriler (musteri_id) ON DELETE CASCADE
);

CREATE TABLE islem_hareketleri (
    islem_id integer GENERATED BY DEFAULT AS IDENTITY,
    gonderen_hesap_id integer,
    alici_hesap_id integer,
    miktar numeric(15,2) NOT NULL,
    aciklama character varying(100),
    islem_tarihi timestamp without time zone DEFAULT (CURRENT_TIMESTAMP),
    CONSTRAINT islem_hareketleri_pkey PRIMARY KEY (islem_id),
    CONSTRAINT fk_alici FOREIGN KEY (alici_hesap_id) REFERENCES hesaplar (hesap_id),
    CONSTRAINT fk_gonderen FOREIGN KEY (gonderen_hesap_id) REFERENCES hesaplar (hesap_id)
);

CREATE UNIQUE INDEX hesaplar_hesap_no_key ON hesaplar (hesap_no);

CREATE INDEX "IX_hesaplar_musteri_id" ON hesaplar (musteri_id);

CREATE INDEX "IX_islem_hareketleri_alici_hesap_id" ON islem_hareketleri (alici_hesap_id);

CREATE INDEX "IX_islem_hareketleri_gonderen_hesap_id" ON islem_hareketleri (gonderen_hesap_id);

CREATE UNIQUE INDEX musteriler_tc_kimlik_no_key ON musteriler (tc_kimlik_no);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260117092647_InitialCreate', '8.0.22');

COMMIT;

