// <auto-generated />
using System;
using BankBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BankBackend.Migrations
{
    [DbContext(typeof(BankDbContext))]
    partial class BankDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BankBackend.Models.GenelIstatistik", b =>
                {
                    b.Property<int>("toplam_islem")
                        .HasColumnType("integer");

                    b.Property<int>("toplam_musteri")
                        .HasColumnType("integer");

                    b.Property<decimal>("toplam_para")
                        .HasColumnType("numeric");

                    b.Property<int>("toplam_risk")
                        .HasColumnType("integer");

                    b.ToTable("GenelIstatistikler");
                });

            modelBuilder.Entity("BankBackend.Models.Hesaplar", b =>
                {
                    b.Property<int>("HesapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("hesap_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HesapId"));

                    b.Property<bool?>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("aktif_mi");

                    b.Property<decimal?>("Bakiye")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("bakiye")
                        .HasDefaultValueSql("0.00");

                    b.Property<string>("HesapNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("hesap_no");

                    b.Property<string>("HesapTuru")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("VADESIZ")
                        .HasColumnName("hesap_turu");

                    b.Property<int>("MusteriId")
                        .HasColumnType("integer")
                        .HasColumnName("musteri_id");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("olusturma_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("HesapId")
                        .HasName("hesaplar_pkey");

                    b.HasIndex("MusteriId");

                    b.HasIndex(new[] { "HesapNo" }, "hesaplar_hesap_no_key")
                        .IsUnique();

                    b.ToTable("hesaplar", (string)null);
                });

            modelBuilder.Entity("BankBackend.Models.IslemHareketleri", b =>
                {
                    b.Property<int>("IslemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("islem_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IslemId"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aciklama");

                    b.Property<int?>("AliciHesapId")
                        .HasColumnType("integer")
                        .HasColumnName("alici_hesap_id");

                    b.Property<int?>("GonderenHesapId")
                        .HasColumnType("integer")
                        .HasColumnName("gonderen_hesap_id");

                    b.Property<DateTime?>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("islem_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Miktar")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("miktar");

                    b.HasKey("IslemId")
                        .HasName("islem_hareketleri_pkey");

                    b.HasIndex("AliciHesapId");

                    b.HasIndex("GonderenHesapId");

                    b.ToTable("islem_hareketleri", (string)null);
                });

            modelBuilder.Entity("BankBackend.Models.Musteriler", b =>
                {
                    b.Property<int>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("musteri_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MusteriId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ad");

                    b.Property<DateTime?>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("kayit_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Rol")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol")
                        .HasDefaultValueSql("'MUSTERI'::character varying");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sifre");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("soyad");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character(11)")
                        .HasColumnName("tc_kimlik_no")
                        .IsFixedLength();

                    b.HasKey("MusteriId")
                        .HasName("musteriler_pkey");

                    b.HasIndex(new[] { "TcKimlikNo" }, "musteriler_tc_kimlik_no_key")
                        .IsUnique();

                    b.ToTable("musteriler", (string)null);
                });

            modelBuilder.Entity("BankBackend.Models.RiskMasasi", b =>
                {
                    b.Property<int>("RiskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("risk_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RiskId"));

                    b.Property<int?>("HesapId")
                        .HasColumnType("integer")
                        .HasColumnName("hesap_id");

                    b.Property<DateTime?>("OlayTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("olay_tarihi")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("SupheliOlay")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("supheli_olay");

                    b.HasKey("RiskId")
                        .HasName("risk_masasi_pkey");

                    b.ToTable("risk_masasi", (string)null);
                });

            modelBuilder.Entity("BankBackend.Models.Hesaplar", b =>
                {
                    b.HasOne("BankBackend.Models.Musteriler", "Musteri")
                        .WithMany("Hesaplars")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_musteri");

                    b.Navigation("Musteri");
                });

            modelBuilder.Entity("BankBackend.Models.IslemHareketleri", b =>
                {
                    b.HasOne("BankBackend.Models.Hesaplar", "AliciHesap")
                        .WithMany("IslemHareketleriAliciHesaps")
                        .HasForeignKey("AliciHesapId")
                        .HasConstraintName("fk_alici");

                    b.HasOne("BankBackend.Models.Hesaplar", "GonderenHesap")
                        .WithMany("IslemHareketleriGonderenHesaps")
                        .HasForeignKey("GonderenHesapId")
                        .HasConstraintName("fk_gonderen");

                    b.Navigation("AliciHesap");

                    b.Navigation("GonderenHesap");
                });

            modelBuilder.Entity("BankBackend.Models.Hesaplar", b =>
                {
                    b.Navigation("IslemHareketleriAliciHesaps");

                    b.Navigation("IslemHareketleriGonderenHesaps");
                });

            modelBuilder.Entity("BankBackend.Models.Musteriler", b =>
                {
                    b.Navigation("Hesaplars");
                });
#pragma warning restore 612, 618
        }
    }
}
